---

- name: "Remove postifx"
  set_fact:
    pei_version: "{{ pu_item.split('-') }}"

- name: "Pull {{ empty_index }}:latest"
  shell: "{{ container_tool }} pull {{ empty_index }}:latest"

- name: "Tag {{ empty_index }}:latest {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}"
  shell: "{{ container_tool }} tag {{ empty_index }}:latest {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}"

- name: "Push {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}"
  shell: "{{ container_tool }} push {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}"

- name: "Tag {{ empty_index }}:latest {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}{{ pu_postfix }}"
  shell: "{{ container_tool }} tag {{ empty_index }}:latest {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}{{ pu_postfix }}"

- name: "Push {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}{{ pu_postfix }}"
  shell: "{{ container_tool }} push {{ default_config.production.index.registry }}/{{ default_config.production.index.organization }}/{{ default_config.production.index.name }}:{{ pei_version[0] }}{{ pu_postfix }}"
